name: DSOPBuilder Test

on: [workflow_dispatch, push]

jobs:
  
  build-container:
    name: Build the DSOPBuilder Container Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Buildx
        run: echo
      - name: Build and export container
        run: echo
      - name: Upload container
        run: echo

  deploy-k8s:
    name: Deploy Kubernetes
    runs-on: ubuntu-latest
    needs: build-container

    steps:
      - name: Setup Buildx
        run: echo
      - name: Download container
        run: echo 
      - name: Load container
        run: echo
      - name: Setup container env (Government)
        run: echo
      - name: Setup container env (Commercial)
        run: echo
      - name: Setup cluster config (rke2)
        run: echo
      - name: Setup cluster config (aks)
        run: echo
      - name: Deploy Kubernetes
        run: echo
      - name: Upload cluster.env
        run: echo

  deploy-bigbang:
    name: Deploy Big Bang
    runs-on: ubuntu-latest
    needs: [build-container, deploy-k8s]

    steps:
      - name: Hello
        run: echo

  verify-bigbang:
    name: Verify Big Bang
    runs-on: ubuntu-latest
    needs: [build-container, deploy-k8s, deploy-bigbang]

    steps:
      - name: Hello
        run: echo

  clean-up:
    name: Destroy all resourcs
    runs-on: ubuntu-22.04
    needs: [build-container, deploy-k8s, deploy-bigbang, verify-bigbang]
    if: ${{ always() }}

    steps:
      - name: Hello
        run: echo