name: Test

on: [workflow_dispatch, push]

jobs:

  build-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Build and export
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: dsopbuilder:ci
          push: false
          outputs: type=docker,dest=/tmp/dsopbuilder-ci.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dsopbuilder
          path: /tmp/dsopbuilder-ci.tar
      
  use-container:
    runs-on: ubuntu-latest
    needs: build-container
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: actions/download-artifact@v3
        with:
          name: dsopbuilder
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/dsopbuilder-ci.tar
          docker image ls -a     
      
      - name: Set up container env
        run: |
          mkdir -p env-tmp

          cat << EOF >  env-tmp/config-rke2.json
          ${{ secrets.RKE2_GOV_CONFIG }}
          EOF

          echo "TIM_TEST=tim_test" >> env-tmp/env.sh

          ls -la env-tmp
      - run: |
          ls env-tmp
      
      - uses: kohlerdominik/docker-run-action@v1
        with:
          image: dsopbuilder:ci
          shell: /bin/bash
          volumes: |
            ${{ github.workspace }}/env-tmp:/env
          run: |
            ls -lah /env
            cat /env/config-rke2.json
            cat /env/env.sh

            source /env/env.sh

            env | grep TIM
