name: Test

on: [workflow_dispatch, push]

jobs:

  build-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Build and export
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: dsopbuilder:ci
          push: false
          outputs: type=docker,dest=/tmp/dsopbuilder-ci.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dsopbuilder
          path: /tmp/dsopbuilder-ci.tar
      
    use-container:
      runs-on: ubuntu-latest
      needs: build-container
      steps:
      - uses: docker/setup-buildx-action@v2
      - uses: actions/download-artifact@v3
        with:
          name: dsopbuilder
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/dsopbuilder-ci.tar
          docker image ls -a     
      - uses: kohlerdominik/docker-run-action@v1
        with:
          image: dsopbuilder:ci
          run: ls -lah
